### PR TITLE
add __get/setstate__

### PR DESCRIPTION
**Pull request by neuper01**
Enable use of pythons pickle module for ufloats and ucomplexs. 

For this functionality the methods __getstate__ and __setstate__ were added.

### CODE REVIEW

**Comment by wollmich** [comment]
Your pull request would serialize the ufloat or ucomplex object to an XML string. But when I take a look at the documentation of the pickle module it says it should be serialized to a byte stream:

> The [pickle](https://docs.python.org/3/library/pickle.html#module-pickle) module implements binary protocols for serializing and de-serializing a Python object structure. “Pickling” is the process whereby a Python object hierarchy is converted into a byte stream, and “unpickling” is the inverse operation, whereby a byte stream (from a [binary file](https://docs.python.org/3/glossary.html#term-binary-file) or [bytes-like object](https://docs.python.org/3/glossary.html#term-bytes-like-object)) is converted back into an object hierarchy.

**Comment by wollmich** [comment]
I'll add `to_byte_array` and  `from_byte_array` static methods to the `ustorage` class.

**Comment by wollmich** [comment]
@neuper01 can you please check on your side if my modification still fulfills your requirements. Once I've your ok I will merge this pull request.

**Comment by neuper01** [comment]
@wollmich Everything still works as intended, thank you very much

**Pull request merged**
